# Site settings
title: Heal the Onion
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Find your relief here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://healtheonion.com" # the base hostname & protocol for your site
twitter_username: 
github_username:

# Build settings
markdown: kramdown
